// Alert groups: nothing rings until turned on; people choose groups; old alerts renamed (30 Sep).
process.env.JWT_SECRET = 't';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
const SET = {};
{ const Setting = R('models/Setting'); Setting.findById = async (k) => (k in SET ? { value: SET[k] } : null); Setting.findOneAndUpdate = async (f, u) => { SET[f._id] = u.$set.value; return {}; }; }
const webpush = R('node_modules/web-push'); const rang = [];
webpush.sendNotification = async (sub, payload) => { rang.push(JSON.parse(payload)); };
const PushSubscription = R('models/PushSubscription');
PushSubscription.find = async (f) => [{ endpoint: 'https://push.example/' + f.ownerId, keys: { p256dh: 'x', auth: 'y' } }];
PushSubscription.updateOne = async () => ({});
const Stylist = R('models/Stylist'), Notification = R('models/Notification'), AlertPref = R('models/AlertPref');
const S = { pro: { _id: 'pro' }, adm: { _id: 'adm', isAdmin: true, accountStatus: 'ACTIVE' } };
Stylist.findById = async (id) => S[String(id)] || null;
const PREFS = {}; const k = (f) => f.ownerType + ':' + f.ownerId;
AlertPref.findOne = async (f) => (PREFS[k(f)] ? { prefs: PREFS[k(f)] } : null);
AlertPref.findOneAndUpdate = async (f, u) => { PREFS[k(f)] = u.prefs; return {}; };
Notification.find = () => ({ sort: () => ({ limit: async () => [{ title: 'Someone joined Sheeba with your code', message: 'Welcome to Sheeba', type: 'INVITE_JOINED' }] }) });
const jwt = R('node_modules/jsonwebtoken'), express = R('node_modules/express');
const { sendPush } = R('lib/push');
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
const app = express(); app.use(express.json()); app.use('/api/push', R('routes/push')); app.use('/api', R('routes/notifications'));
app.use((err, req, res, next) => { console.log('SERVER ERROR', err.message); res.status(500).json({ error: 'x' }); });
const server = app.listen(0, async () => {
  const port = server.address().port;
  const call = async (m, u, tok, body) => { const r = await fetch(`http://localhost:${port}${u}`, { method: m, headers: { 'Content-Type': 'application/json', ...(tok ? { Authorization: 'Bearer ' + tok } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { s: r.status, j: await r.json() }; };
  const PRO = jwt.sign({ id: 'pro' }, 't'), ADM = jwt.sign({ id: 'adm' }, 't'), AMA = jwt.sign({ id: 'ama', role: 'customer' }, 't');
  let r = await call('GET', '/api/push/prefs', AMA);
  check('a customer sees her groups (no team, no admin work)', r.s === 200 && r.j.groups.join() === 'bookings,messages,looks,rewards,account');
  check('starting choice: bookings, messages and account on; the rest off', r.j.prefs.bookings && r.j.prefs.messages && r.j.prefs.account && !r.j.prefs.looks && !r.j.prefs.rewards);
  r = await call('GET', '/api/push/prefs', PRO);
  check('a professional also sees Team and training, but not Admin work', r.j.groups.includes('team') && !r.j.groups.includes('admin'));
  r = await call('GET', '/api/push/prefs', ADM);
  check('an admin also sees Admin work', r.j.groups.includes('admin'));
  rang.length = 0;
  await sendPush('stylist', 'pro', { title: 'New booking request from Ama', tag: 'REQUEST_CREATED' });
  await sendPush('stylist', 'pro', { title: 'Nky credited you', tag: 'RATING_RECEIVED' });
  check('with the starting choice: the booking rings, the rating does not', rang.length === 1 && rang[0].title === 'New booking request from Ama');
  r = await call('PUT', '/api/push/prefs', PRO, { prefs: { looks: true, bookings: false, hacker: true, messages: 'yes' } });
  const saved = PREFS['stylist:pro'];
  check('he switches Looks on and Bookings off (junk ignored)', r.s === 200 && saved.looks === true && saved.bookings === false && !('hacker' in saved) && saved.messages === true);
  rang.length = 0;
  await sendPush('stylist', 'pro', { title: 'booking', tag: 'REQUEST_CREATED' });
  await sendPush('stylist', 'pro', { title: 'rating', tag: 'RATING_RECEIVED' });
  check('now the rating rings and the booking does not, exactly as he chose', rang.length === 1 && rang[0].title === 'rating');
  rang.length = 0;
  await sendPush('stylist', 'pro', { title: 'test', tag: 'test' });
  check('"Send me a test" always rings', rang.length === 1);
  check('not logged in → cannot read or change anyone\'s choices', (await call('GET', '/api/push/prefs')).s === 401 && (await call('PUT', '/api/push/prefs', null, { prefs: {} })).s === 401);
  r = await call('GET', '/api/notifications', PRO);
  check('old alerts saved before the rename show "Mepluge"', r.j[0].title === 'Someone joined Mepluge with your code' && r.j[0].message === 'Welcome to Mepluge');
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); server.close(); process.exit(fail ? 1 : 0);
});
