// Community feedback from Telegram reaches the admin (29 Sep audit fix).
process.env.JWT_SECRET = 't'; process.env.PAYSTACK_SECRET_KEY = 't';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
{ const Setting = R('models/Setting'); Setting.findById = async () => null; }
const jwt = R('node_modules/jsonwebtoken'), express = R('node_modules/express');
const Stylist = R('models/Stylist'), CommunityFeedback = R('models/CommunityFeedback'), Notification = R('models/Notification');
const doc = (f) => ({ ...f, _id: { toString: () => f.id } });
const S = { chris: doc({ id: 'chris', isAdmin: true, accountStatus: 'ACTIVE' }), mo: doc({ id: 'mo', adminRole: 'MODERATOR', accountStatus: 'ACTIVE' }), sue: doc({ id: 'sue', adminRole: 'SUPPORT', accountStatus: 'ACTIVE' }) };
const FB = { f1: { _id: 'f1', senderName: 'Ama', text: 'Can you add pedicure in Ho?', handled: false } }, notes = [];
Stylist.findById = async (id) => S[String(id)] || null;
Stylist.find = async (f) => Object.values(S).filter((s) => (f.$or || []).some((x) => (x.isAdmin && s.isAdmin) || (x.adminRole && s.adminRole)));
CommunityFeedback.find = () => ({ sort: () => ({ limit: async () => Object.values(FB) }) });
CommunityFeedback.findByIdAndUpdate = async (id, u) => { if (String(id).includes('!')) throw new Error('Cast'); const f = FB[id]; if (f) Object.assign(f, u); return f || null; };
Notification.create = async (n) => { notes.push(n); return n; };
const app = express(); app.use(express.json()); app.use('/api/telegram', R('routes/telegram'));
app.use((err, req, res, next) => { console.log('SERVER ERROR', err.message); res.status(500).json({ error: 'x' }); });
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
const server = app.listen(0, async () => {
  const port = server.address().port;
  const call2 = async (m, u, who, body) => { const r = await fetch(`http://localhost:${port}${u}`, { method: m, headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + jwt.sign({ id: who }, 't') }, body: body ? JSON.stringify(body) : undefined }); let j = {}; try { j = await r.json(); } catch (e) {} return { s: r.status, j }; };
  const call = async (m, u, who) => { const r = await fetch(`http://localhost:${port}${u}`, { method: m, headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + jwt.sign({ id: who }, 't') } }); let j = {}; try { j = await r.json(); } catch (e) {} return { s: r.status, j }; };
  let r;
  check('a Moderator can read community feedback', (await call('GET', '/api/telegram/feedback', 'mo')).s === 200);
  check('Support cannot', (await call('GET', '/api/telegram/feedback', 'sue')).s === 403);
  r = await call('PUT', '/api/telegram/feedback/f1/handled', 'mo');
  check('a Moderator marks it handled', r.s === 200 && FB.f1.handled === true);
  check('a bad link gets a clean 404 (no crash)', (await call('PUT', '/api/telegram/feedback/bad!id/handled', 'mo')).s === 404);
  const { notifyAllAdmins } = R('routes/notifications');
  await notifyAllAdmins({ type: 'COMMUNITY_FEEDBACK', title: 'Community: Ama', entityType: 'admin' });
  check('new community feedback alerts Christopher and the Moderator (not Support)', notes.map((n) => n.recipientId).sort().join() === 'chris,mo', notes.map((n) => n.recipientId).join());
  console.log('--- CONNECTING AND ANSWERING (stand-in Telegram) ---');
  const realFetch = global.fetch; const sent = []; let tgOk = true;
  global.fetch = async (url, opts) => {
    if (!String(url).includes('api.telegram.org')) return realFetch(url, opts);
    const method = String(url).split('/').pop(); const body = JSON.parse(opts.body || '{}'); sent.push({ method, body, url: String(url) });
    if (!tgOk) return { json: async () => ({ ok: false, description: 'Bad Request: chat not found' }) };
    if (method === 'getMe') return { json: async () => ({ ok: true, result: { username: 'SheebaHelpBot' } }) };
    if (method === 'getWebhookInfo') return { json: async () => ({ ok: true, result: { url: 'https://sheeba-mavio.onrender.com/api/telegram/webhook' } }) };
    return { json: async () => ({ ok: true, result: {} }) };
  };
  delete process.env.TELEGRAM_BOT_TOKEN; delete process.env.TELEGRAM_WEBHOOK_SECRET;
  r = await call('GET', '/api/telegram/status', 'mo');
  check('status says plainly what is missing (no token, no secret yet)', r.s === 200 && r.j.tokenSet === false && r.j.secretSet === false && r.j.connected === false);
  check('connecting without the token and secret explains what to add', (await call('POST', '/api/telegram/connect', 'mo')).s === 400);
  process.env.TELEGRAM_BOT_TOKEN = '123:ABC'; process.env.TELEGRAM_WEBHOOK_SECRET = 's3cret'; process.env.RENDER_EXTERNAL_URL = 'https://sheeba-mavio.onrender.com';
  r = await call('POST', '/api/telegram/connect', 'mo');
  const hook = sent.find((x) => x.method === 'setWebhook');
  check('one tap connects: the bot is pointed at our webhook, WITH the secret, messages only', r.s === 200 && hook.body.url === 'https://sheeba-mavio.onrender.com/api/telegram/webhook' && hook.body.secret_token === 's3cret' && hook.body.allowed_updates.join() === 'message');
  r = await call('GET', '/api/telegram/status', 'mo');
  check('status: connected, bot @SheebaHelpBot', r.j.connected === true && r.j.bot === 'SheebaHelpBot');
  check('Support cannot connect Telegram', (await call('POST', '/api/telegram/connect', 'sue')).s === 403);
  const F2 = { _id: 'f2', telegramChatId: -100123, telegramMessageId: 77, senderName: 'Kojo', text: 'Is there a barber in Ho?', handled: false, replies: [], save: async function () { return this; } };
  CommunityFeedback.findById = async (id) => { if (String(id).includes('!')) throw new Error('Cast'); return id === 'f2' ? F2 : null; };
  S.mo.name = 'Mo';
  check('an empty answer is refused', (await call2('POST', '/api/telegram/feedback/f2/reply', 'mo', { text: ' ' })).s === 400);
  r = await call2('POST', '/api/telegram/feedback/f2/reply', 'mo', { text: 'Yes! Search "barber in Ho" on Sheeba.' });
  const msg = sent.filter((x) => x.method === 'sendMessage').pop();
  check("the answer is posted in the group as a reply to Kojo's message", r.s === 200 && msg.body.chat_id === -100123 && msg.body.reply_parameters.message_id === 77 && /barber in Ho/.test(msg.body.text));
  check('the answer is saved with who answered, and the question is marked handled', F2.replies.length === 1 && F2.replies[0].byName === 'Mo' && F2.handled === true);
  tgOk = false; F2.replies = []; F2.handled = false;
  r = await call2('POST', '/api/telegram/feedback/f2/reply', 'mo', { text: 'Second try' });
  check('if Telegram refuses, it says why and NOTHING is saved as answered', r.s === 502 && /chat not found/.test(r.j.error) && F2.replies.length === 0 && F2.handled === false);
  check('a bad link gets a clean 404', (await call2('POST', '/api/telegram/feedback/bad!id/reply', 'mo', { text: 'hi there' })).s === 404);
  check('Support cannot answer', (await call2('POST', '/api/telegram/feedback/f2/reply', 'sue', { text: 'hi there' })).s === 403);
  global.fetch = realFetch;
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); server.close(); process.exit(fail ? 1 : 0);
});
