// Continue with Google: real signature checks, sign-in, sign-up, connect, privacy (30 Sep).
process.env.JWT_SECRET = 't'; process.env.PAYSTACK_SECRET_KEY = 't'; process.env.GOOGLE_CLIENT_ID = 'mepluge-client.apps.googleusercontent.com';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
{ const Setting = R('models/Setting'); Setting.findById = async () => null; }
const crypto = require('crypto'), jwt = R('node_modules/jsonwebtoken'), express = R('node_modules/express');
const Stylist = R('models/Stylist'), Customer = R('models/Customer'), Counter = R('models/Counter'), Notification = R('models/Notification'), Activity = R('models/Activity');
const { verifyGoogleIdToken, _resetGoogleCacheForTests } = R('lib/google');
const attempts = R('lib/attempts'); attempts._setNowForTests(() => 1e12);
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
// A real RSA key standing in for Google's; its public half is "published" at Google's address.
const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', { modulusLength: 2048 });
const jwk = { ...publicKey.export({ format: 'jwk' }), kid: 'k1', alg: 'RS256', use: 'sig' };
const realFetch = global.fetch;
global.fetch = async (url, opts) => (String(url).includes('googleapis.com/oauth2/v3/certs') ? { json: async () => ({ keys: [jwk] }), headers: { get: () => 'max-age=3600' } } : realFetch(url, opts));
const b64u = (o) => Buffer.from(typeof o === 'string' ? o : JSON.stringify(o)).toString('base64url');
const google = (claims = {}, { key = privateKey, kid = 'k1' } = {}) => {
  const h = b64u({ alg: 'RS256', kid, typ: 'JWT' });
  const p = b64u({ iss: 'https://accounts.google.com', aud: process.env.GOOGLE_CLIENT_ID, sub: 'g-111', email: 'Ama@Gmail.com', email_verified: true, name: 'Ama Owusu', exp: Math.floor(Date.now() / 1000) + 600, ...claims });
  return `${h}.${p}.${crypto.sign('RSA-SHA256', Buffer.from(`${h}.${p}`), key).toString('base64url')}`;
};
// Stand-in accounts.
let seq = 40; const P = [], C = [];
const doc = (f) => ({ ...f, _id: { toString: () => f.id }, save: async function () { return this; }, toObject() { const { toObject, save, ...r } = this; return JSON.parse(JSON.stringify(r)); } });
const finder = (L) => async (f) => L.find((d) => (f.googleSub ? d.googleSub === f.googleSub : f.phone ? f.phone.$in.includes(d.phone) : false)) || null;
Stylist.findOne = finder(P); Customer.findOne = finder(C);
Stylist.exists = async (f) => P.some((d) => d.googleSub === f.googleSub); Customer.exists = async (f) => C.some((d) => d.googleSub === f.googleSub);
Stylist.findById = async (id) => P.find((d) => d.id === String(id)) || null; Customer.findById = async (id) => C.find((d) => d.id === String(id)) || null;
Stylist.create = async (f) => { const d = doc({ id: 'p' + P.length, ...f }); P.push(d); return d; };
Customer.create = async (f) => { const d = doc({ id: 'c' + C.length, ...f }); C.push(d); return d; };
Stylist.find = async () => []; Counter.findById = async () => ({ seq }); Counter.findOneAndUpdate = async () => ({ seq: ++seq });
Notification.create = async () => ({}); Activity.create = async () => ({});
const app = express(); app.set('trust proxy', 1); app.use(express.json());
app.use('/api/auth', R('routes/auth')); app.use('/api/customers', R('routes/customers')); app.use('/api/settings', R('routes/settings')); app.use('/api/stylists', R('routes/stylists'));
app.use((err, req, res, next) => { console.log('SERVER ERROR', err.message); res.status(500).json({ error: 'x' }); });
const server = app.listen(0, async () => {
  const port = server.address().port; let ip = 0;
  const post = async (u, body, token) => { const r = await fetch(`http://localhost:${port}${u}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Forwarded-For': '10.3.0.' + (++ip), ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: JSON.stringify(body) }); return { s: r.status, j: await r.json() }; };
  console.log('--- CHECKING GOOGLE SIGN-INS ---');
  let g = await verifyGoogleIdToken(google());
  check('a real Google sign-in is accepted: id, email (lower case), name', g.sub === 'g-111' && g.email === 'ama@gmail.com' && g.name === 'Ama Owusu');
  const bad = async (t) => { try { await verifyGoogleIdToken(t); return false; } catch (e) { return true; } };
  const { privateKey: forger } = crypto.generateKeyPairSync('rsa', { modulusLength: 2048 });
  check('FORGED: signed with someone else\'s key → refused', await bad(google({}, { key: forger })));
  const t = google(); const parts = t.split('.'); parts[1] = b64u({ ...JSON.parse(Buffer.from(parts[1], 'base64url')), email: 'boss@gmail.com' });
  check('TAMPERED: email changed after signing → refused', await bad(parts.join('.')));
  check('meant for ANOTHER app (wrong client id) → refused', await bad(google({ aud: 'someone-else.apps.googleusercontent.com' })));
  check('not issued by Google → refused', await bad(google({ iss: 'https://evil.example' })));
  check('expired → refused', await bad(google({ exp: Math.floor(Date.now() / 1000) - 3600 })));
  check('email not confirmed by Google → refused', await bad(google({ email_verified: false })));
  check('junk → refused', await bad('not.a.token') && await bad(undefined));
  _resetGoogleCacheForTests();
  console.log('--- A NEW CUSTOMER ---');
  let r = await post('/api/customers/google', { credential: google() });
  check('first time with Google: asked to finish (phone), name and email filled in', r.s === 200 && r.j.needsSignup === true && r.j.name === 'Ama Owusu' && r.j.email === 'ama@gmail.com');
  r = await post('/api/customers/register', { googleCredential: google(), phone: '0241112222', country: 'GH', marketingOptIn: true });
  const ama = C[0];
  check('sign-up with Google + phone: no password needed, name from Google', r.s === 200 && r.j.token && ama.name === 'Ama Owusu' && ama.phone === '+233241112222');
  check('…the account keeps the Google id, a CONFIRMED email and the news opt-in', ama.googleSub === 'g-111' && ama.email === 'ama@gmail.com' && ama.emailVerified === true && ama.marketingOptIn === true);
  check('…it still gets a member number and a code like everyone', ama.memberNumber > 40 && ama.code);
  check('…the reply never includes the Google id or password hash', !JSON.stringify(r.j).includes('g-111') && !JSON.stringify(r.j).includes('passwordHash') && r.j.customer.googleConnected === true);
  r = await post('/api/customers/register', { googleCredential: google(), phone: '0241119999', country: 'GH' });
  check('the same Google account cannot make a second account', r.s === 400);
  r = await post('/api/customers/google', { credential: google() });
  check('next time: Continue with Google logs her straight in', r.s === 200 && r.j.token && r.j.customer.name === 'Ama Owusu');
  r = await post('/api/customers/register', { googleCredential: google({}, { key: forger }), phone: '0241110000', country: 'GH' });
  check('a forged Google sign-up is refused', r.s === 401 && C.length === 1);
  console.log('--- A PROFESSIONAL ---');
  r = await post('/api/auth/google', { credential: google({ sub: 'g-222', email: 'kojo@gmail.com', name: 'Kojo Barber' }) });
  check('new professional with Google: asked to finish', r.j.needsSignup === true);
  r = await post('/api/auth/register', { googleCredential: google({ sub: 'g-222', email: 'kojo@gmail.com', name: 'Kojo Barber' }), phone: '0551234567', country: 'GH' });
  const kojo = P[0];
  check('his shop is created through the normal sign-up (starts hidden until approved)', r.s === 200 && kojo.googleSub === 'g-222' && kojo.status === 'UNDER_REVIEW' && kojo.email === 'kojo@gmail.com');
  kojo.accountStatus = 'SUSPENDED'; kojo.restrictionReason = 'Reports under review';
  r = await post('/api/auth/google', { credential: google({ sub: 'g-222', email: 'kojo@gmail.com' }) });
  check('a suspended account cannot log in with Google either, and is told why', r.s === 403 && /Reports under review/.test(r.j.error));
  kojo.accountStatus = 'ACTIVE';
  console.log('--- CONNECTING GOOGLE TO AN EXISTING ACCOUNT ---');
  P.push(doc({ id: 'old', name: 'Efua', phone: '+233201112222', status: 'APPROVED', accountStatus: 'ACTIVE', googleSub: null }));
  const EFUA = jwt.sign({ id: 'old' }, 't');
  r = await post('/api/auth/google-connect', { credential: google({ sub: 'g-333', email: 'efua@gmail.com' }) }, EFUA);
  check('Efua (phone account) connects Google: from now on she can use it', r.s === 200 && P.find((d) => d.id === 'old').googleSub === 'g-333');
  r = await post('/api/auth/google-connect', { credential: google({ sub: 'g-222', email: 'kojo@gmail.com' }) }, EFUA);
  check("she cannot take over Kojo's Google account", r.s === 409 && P.find((d) => d.id === 'old').googleSub === 'g-333');
  console.log('--- PRIVACY ---');
  Stylist.findById = async (id) => P.find((d) => d.id === String(id)) || null;
  const R2 = R('models/Request'); R2.countDocuments = async () => 0; R2.find = async () => [];
  const pub = await fetch(`http://localhost:${port}/api/stylists/old`).then((x) => x.json());
  check("the public shop page shows NO email, Google id, news choice or sign-up source", !('email' in pub) && !('googleSub' in pub) && !('marketingOptIn' in pub) && !('signupSource' in pub), Object.keys(pub).join(','));
  const st = await fetch(`http://localhost:${port}/api/settings`).then((x) => x.json());
  check('the app learns the (public) Google client id, so it can show the button', st.googleClientId === process.env.GOOGLE_CLIENT_ID);
  delete process.env.GOOGLE_CLIENT_ID;
  r = await post('/api/customers/google', { credential: google() });
  check('with no Google key set on the server: politely not available', r.s === 401 && /not set up/.test(r.j.error));
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); server.close(); process.exit(fail ? 1 : 0);
});
