// Messages, customer notes and earnings (27 Sep).
process.env.JWT_SECRET = 't'; process.env.PAYSTACK_SECRET_KEY = 't';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
// Admin switches: a stand-in returning nothing, so every switch uses its safe default (instant, no database).
{ const Setting = require(path.join(B, 'models/Setting')); Setting.findById = async () => null; }
const jwt = R('node_modules/jsonwebtoken'), express = R('node_modules/express');
const Stylist = R('models/Stylist'), Customer = R('models/Customer'), Request = R('models/Request'), CustomerNote = R('models/CustomerNote');
const Conversation = R('models/Conversation'), Message = R('models/Message'), Notification = R('models/Notification'), RepeatPreference = R('models/RepeatPreference');
const attempts = R('lib/attempts'); attempts._setNowForTests(() => 1e12);
let seq = 0; const DAY = 86400000, now = Date.now();
const doc = (f) => ({ ...f, _id: { toString: () => f.id, toJSON: () => f.id }, save: async function () { return this; } });
const S = { pro: doc({ id: 'pro', name: 'Etornam', status: 'APPROVED', accountStatus: 'ACTIVE' }), pend: doc({ id: 'pend', name: 'New', status: 'UNDER_REVIEW', accountStatus: 'ACTIVE' }), adm: doc({ id: 'adm', name: 'Admin', isAdmin: true, status: 'APPROVED', accountStatus: 'ACTIVE' }) };
for (let i = 0; i < 12; i++) S['s' + i] = doc({ id: 's' + i, name: 'Shop ' + i, status: 'APPROVED', accountStatus: 'ACTIVE' });
const C = { ama: doc({ id: 'ama', name: 'Ama', accountStatus: 'ACTIVE' }), bad: doc({ id: 'bad', name: 'Bad', accountStatus: 'RESTRICTED' }), yaw: doc({ id: 'yaw', name: 'Yaw', accountStatus: 'ACTIVE' }) };
const RQ = {
  old: doc({ id: 'old', stylistId: 'pro', clientId: 'ama', status: 'completed', priceSnapshot: 300, currencySnapshot: 'GHS', serviceNameSnapshot: 'Knotless', completedAt: now - 40 * DAY, updatedAt: now }),
  leg: doc({ id: 'leg', stylistId: 'pro', clientId: 'yaw', status: 'completed', priceSnapshot: 100, currencySnapshot: 'GHS', serviceNameSnapshot: 'Cornrows', updatedAt: now - 3600 * 1000 }),
};
const NOTES = {}, CONV = {}, MSG = [];
const get = (T) => async (id) => { if (String(id).includes('!')) throw new Error('Cast'); return T[String(id)] || null; };
Stylist.findById = get(S); Customer.findById = get(C);
Request.find = (f) => { const l = Object.values(RQ).filter((r) => Object.entries(f).every(([k, v]) => r[k] === v)); const p = Promise.resolve(l); p.sort = () => Promise.resolve(l); return p; };
Request.exists = async (f) => Object.values(RQ).some((r) => r.stylistId === f.stylistId && r.clientId === f.clientId);
CustomerNote.create = async (f) => { const id = 'n' + (++seq); NOTES[id] = doc({ id, ...f }); return NOTES[id]; };
CustomerNote.findOne = async (f) => { if (String(f._id).includes('!')) throw new Error('Cast'); const n = NOTES[f._id]; return n && n.stylistId === f.stylistId && n.customerId === f.customerId ? n : null; };
CustomerNote.deleteOne = async (f) => { delete NOTES[String(f._id)]; };
RepeatPreference.find = async () => [];
let convDateArg = null;
Conversation.findOne = async (f) => Object.values(CONV).find((c) => c.customerId === f.customerId && c.stylistId === f.stylistId) || null;
Conversation.countDocuments = async (f) => { convDateArg = f.createdAt.$gte; return Object.values(CONV).filter((c) => c.customerId === f.customerId && c.createdAt >= f.createdAt.$gte).length; };
Conversation.create = async (f) => { const id = 'c' + (++seq); CONV[id] = doc({ id, createdAt: new Date(), ...f }); return CONV[id]; };
Conversation.findById = get(CONV);
Message.create = async (f) => { MSG.push(f); return f; };
Message.find = () => { const p = Promise.resolve(MSG); p.sort = () => Promise.resolve(MSG); return p; };
const notes = []; Notification.create = async (n) => { notes.push(n); return n; };
const app = express(); app.use(express.json({ limit: '2mb' }));
app.use('/api/stylists', R('routes/crm')); app.use('/api', R('routes/messages'));
app.use((err, req, res, next) => { console.log('SERVER ERROR', err.message); res.status(500).json({ error: 'x' }); });
const tok = (p) => jwt.sign(p, 't'); const PRO = tok({ id: 'pro' }), ADMIN = tok({ id: 'adm', isAdmin: true }), AMA = tok({ id: 'ama', role: 'customer' }), BAD = tok({ id: 'bad', role: 'customer' }), YAW = tok({ id: 'yaw', role: 'customer' });
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
const server = app.listen(8227, async () => {
  const call = async (m, u, t, body) => { const r = await fetch('http://localhost:8227' + u, { method: m, headers: { 'Content-Type': 'application/json', ...(t ? { Authorization: 'Bearer ' + t } : {}) }, body: body ? JSON.stringify(body) : undefined }); let j = {}; try { j = await r.json(); } catch (e) {} return { s: r.status, j }; };
  console.log('--- EARNINGS DATED BY COMPLETION ---');
  let r = await call('GET', '/api/stylists/me/service-value?period=today', PRO);
  check('a job done 40 days ago but RATED today does not count as today', r.s === 200 && !r.j.byService.some((x) => x.name === 'Knotless'), JSON.stringify(r.j.byService));
  check('an older booking without a completion date still counts (falls back)', r.j.byService.some((x) => x.name === 'Cornrows') && r.j.recordedServiceValueByCurrency.GHS.total === 100);
  r = await call('GET', '/api/stylists/me/service-value?period=all', PRO);
  check('all time: both, GH₵400 recorded (labelled service value, not payments)', r.j.recordedServiceValueByCurrency.GHS.total === 400 && r.j.completedCount === 2);
  console.log('--- PRIVATE NOTES ---');
  r = await call('POST', '/api/stylists/me/customers/ama/notes', PRO, { note: 'x'.repeat(1001) });
  check('an over-long note is refused', r.s === 400);
  r = await call('POST', '/api/stylists/me/customers/ama/notes', PRO, { note: '  Prefers medium knotless, sensitive scalp.  ' });
  const nid = Object.keys(NOTES)[0];
  check('note saved (tidied)', r.s === 200 && NOTES[nid].note === 'Prefers medium knotless, sensitive scalp.');
  r = await call('DELETE', `/api/stylists/me/customers/ama/notes/${nid}`, tok({ id: 'other-pro' }));
  check('another professional cannot delete it', r.s === 404 && NOTES[nid]);
  r = await call('DELETE', `/api/stylists/me/customers/ama/notes/${nid}`, PRO);
  check('the author can delete their own note', r.s === 200 && !NOTES[nid]);
  r = await call('DELETE', '/api/stylists/me/customers/ama/notes/bad!id', PRO);
  check('bad note id → clean 404', r.s === 404);
  console.log('--- STARTING CONVERSATIONS ---');
  r = await call('POST', '/api/conversations', AMA, { stylistId: 'pend' });
  check('a shop that is not approved cannot be messaged', r.s === 404);
  r = await call('POST', '/api/conversations', BAD, { stylistId: 'pro' });
  check('a restricted customer cannot start conversations', r.s === 403);
  r = await call('POST', '/api/conversations', AMA, { stylistId: 'pro' });
  check('a customer can message a live shop (ask before booking)', r.s === 200 && r.j.stylistId === 'pro');
  for (let i = 0; i < 9; i++) await call('POST', '/api/conversations', AMA, { stylistId: 's' + i });
  r = await call('POST', '/api/conversations', AMA, { stylistId: 's10' });
  check('11th NEW conversation in 24 hours → paused', r.s === 429);
  check('the daily count really uses a date (the stored type)', convDateArg instanceof Date);
  r = await call('POST', '/api/conversations', AMA, { stylistId: 'pro' });
  check('re-opening an existing conversation is always fine', r.s === 200);
  console.log('--- SENDING MESSAGES ---');
  const cid = Object.values(CONV).find((c) => c.stylistId === 'pro').id;
  r = await call('POST', `/api/conversations/${cid}/messages`, AMA, { text: 'x'.repeat(2001) });
  check('an over-long message is refused', r.s === 400);
  r = await call('POST', `/api/conversations/${cid}/messages`, AMA, { photo: 'https://tracker.example/pixel.png' });
  check('TRACKING: a web-address "photo" is refused', r.s === 400);
  r = await call('POST', `/api/conversations/${cid}/messages`, AMA, { text: '  Is Saturday free?  ' });
  check('a normal message goes through (tidied)', r.s === 200 && MSG.at(-1).text === 'Is Saturday free?');
  r = await call('POST', `/api/conversations/${cid}/messages`, YAW, { text: 'hi' });
  check('someone outside the conversation cannot send into it', r.s === 403);
  r = await call('POST', `/api/conversations/${cid}/messages`, ADMIN, { text: 'hi' });
  check('the admin cannot send as either person', r.s === 403);
  r = await call('GET', `/api/conversations/${cid}/messages`, ADMIN);
  check('…but can read it when handling a report', r.s === 200);
  r = await call('GET', '/api/conversations/bad!id/messages', AMA);
  check('bad conversation link → clean 404 (no crash)', r.s === 404);
  r = await call('POST', `/api/conversations/${cid}/messages`, PRO, { text: 'Saturday 10am works' });
  check('a professional replies: the customer is told "New message from Etornam" (the shop, not "your stylist")', r.s === 200 && notes.some((n) => n.recipientId === 'ama' && n.title === 'New message from Etornam'), JSON.stringify(notes.map((n) => n.title)));
  S.pro.accountStatus = 'RESTRICTED';
  r = await call('POST', `/api/conversations/${cid}/messages`, PRO, { text: 'Hello' });
  check('a restricted professional cannot send messages', r.s === 403);
  S.pro.accountStatus = 'ACTIVE';
  for (let i = 0; i < 29; i++) await call('POST', `/api/conversations/${cid}/messages`, PRO, { text: 'msg ' + i }); // + the reply above = 30
  r = await call('POST', `/api/conversations/${cid}/messages`, PRO, { text: 'one too many' });
  check('flooding: 30 messages allowed, the 31st within 15 minutes → paused', r.s === 429, r.s);
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); server.close(); process.exit(fail ? 1 : 0);
});
