// Phone alerts (Web Push): keys, subscribing, who gets what, cleanup (30 Sep).
process.env.JWT_SECRET = 't'; process.env.PAYSTACK_SECRET_KEY = 't';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
const SET = {}; let keyWrites = 0;
{ const Setting = R('models/Setting'); Setting.findById = async (k) => (k in SET ? { value: SET[k] } : null); Setting.findOneAndUpdate = async (f, u) => { keyWrites++; SET[f._id] = u.$set.value; return {}; }; }
const webpush = R('node_modules/web-push');
const realKeys = webpush.generateVAPIDKeys; let generated = 0;
webpush.generateVAPIDKeys = () => { generated++; return realKeys(); };
const delivered = []; const gone = new Set();
webpush.sendNotification = async (sub, payload) => { if (gone.has(sub.endpoint)) { const e = new Error('Gone'); e.statusCode = 410; throw e; } delivered.push({ endpoint: sub.endpoint, ...JSON.parse(payload) }); };
const PushSubscription = R('models/PushSubscription');
let SUBS = [];
PushSubscription.findOneAndUpdate = async (f, u) => { let s = SUBS.find((x) => x.endpoint === f.endpoint); if (!s) { s = { endpoint: f.endpoint }; SUBS.push(s); } Object.assign(s, u); return s; };
PushSubscription.find = async (f) => SUBS.filter((s) => s.ownerType === f.ownerType && s.ownerId === f.ownerId);
PushSubscription.deleteOne = async (f) => { SUBS = SUBS.filter((s) => !(s.endpoint === f.endpoint && (!f.ownerId || (s.ownerId === f.ownerId && s.ownerType === f.ownerType)))); };
PushSubscription.updateOne = async () => ({});
const jwt = R('node_modules/jsonwebtoken'), express = R('node_modules/express');
const { publicKey, sendPush } = R('lib/push');
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
const phone = (n) => ({ endpoint: `https://fcm.googleapis.com/fcm/send/phone-${n}-abcdefgh`, keys: { p256dh: 'B' + 'x'.repeat(86), auth: 'a'.repeat(22) } });
const app = express(); app.use(express.json()); app.use('/api/push', R('routes/push'));
app.use((err, req, res, next) => { console.log('SERVER ERROR', err.message); res.status(500).json({ error: 'x' }); });
const server = app.listen(0, async () => {
  const port = server.address().port;
  const call = async (m, u, tok, body) => { const r = await fetch(`http://localhost:${port}${u}`, { method: m, headers: { 'Content-Type': 'application/json', ...(tok ? { Authorization: 'Bearer ' + tok } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { s: r.status, j: await r.json() }; };
  const PRO = jwt.sign({ id: 'etornam' }, 't'), AMA = jwt.sign({ id: 'ama', role: 'customer' }, 't'), YAW = jwt.sign({ id: 'yaw', role: 'customer' }, 't');
  console.log('--- SECURITY KEYS ---');
  let r = await call('GET', '/api/push/public-key');
  const k1 = r.j.key;
  check('the public key is created the first time (nothing to set up)', r.s === 200 && typeof k1 === 'string' && k1.length > 60 && generated === 1 && keyWrites === 1);
  r = await call('GET', '/api/push/public-key');
  check('…and REUSED after that (phones keep working)', r.j.key === k1 && generated === 1);
  check('the private key is never sent out', !JSON.stringify(r.j).includes(SET.vapidKeys.privateKey));
  console.log('--- ASKING FOR ALERTS ---');
  check('not logged in → refused', (await call('POST', '/api/push/subscribe', null, { subscription: phone(1) })).s === 401);
  check('a non-https address is refused', (await call('POST', '/api/push/subscribe', PRO, { subscription: { ...phone(1), endpoint: 'http://evil.example/x' } })).s === 400);
  check('broken keys are refused', (await call('POST', '/api/push/subscribe', PRO, { subscription: { ...phone(1), keys: { p256dh: '<script>', auth: 'x' } } })).s === 400);
  r = await call('POST', '/api/push/subscribe', PRO, { subscription: phone(1) });
  check("Etornam's phone signs up for alerts", r.s === 200 && SUBS.length === 1 && SUBS[0].ownerId === 'etornam' && SUBS[0].ownerType === 'stylist');
  await call('POST', '/api/push/subscribe', AMA, { subscription: phone(2) });
  check("Ama's phone too (as a customer)", SUBS.find((s) => s.ownerId === 'ama').ownerType === 'customer');
  console.log('--- WHO GETS WHAT ---');
  let n = await sendPush('stylist', 'etornam', { title: 'New booking request from Ama', body: 'Knotless, Saturday 10am', url: '/notifications' });
  check("a booking alert reaches Etornam's phone only", n === 1 && delivered.length === 1 && delivered[0].endpoint === phone(1).endpoint && delivered[0].title === 'New booking request from Ama');
  n = await sendPush('customer', 'etornam', { title: 'x' });
  check('the same id as a CUSTOMER gets nothing (types never mix)', n === 0);
  r = await call('POST', '/api/push/test', AMA);
  check('"Send me a test" rings only her own phone', r.j.sent === 1 && delivered.at(-1).endpoint === phone(2).endpoint && /alerts are on/.test(delivered.at(-1).title));
  console.log('--- CLEANING UP ---');
  gone.add(phone(2).endpoint);
  n = await sendPush('customer', 'ama', { title: 'Your fresh look' });
  check('a phone that uninstalled (410) is forgotten automatically', n === 0 && !SUBS.some((s) => s.endpoint === phone(2).endpoint));
  await call('POST', '/api/push/subscribe', YAW, { subscription: phone(1) });
  check('a phone that changes hands alerts its NEW owner only', SUBS.find((s) => s.endpoint === phone(1).endpoint).ownerId === 'yaw');
  r = await call('POST', '/api/push/unsubscribe', PRO, { endpoint: phone(1).endpoint });
  check("someone can't switch off another person's phone", SUBS.some((s) => s.endpoint === phone(1).endpoint));
  await call('POST', '/api/push/unsubscribe', YAW, { endpoint: phone(1).endpoint });
  check('the owner can switch alerts off', !SUBS.some((s) => s.endpoint === phone(1).endpoint));
  for (let i = 10; i < 22; i++) await call('POST', '/api/push/subscribe', PRO, { subscription: phone(i) });
  check('at most 10 phones per person (the oldest drop off)', SUBS.filter((s) => s.ownerId === 'etornam').length === 10);
  const Notification = R('models/Notification');
  check('EVERY alert type flows to phones (hooked once, on the alert itself)', Notification.schema.s.hooks._posts.get('save').length >= 1);
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); server.close(); process.exit(fail ? 1 : 0);
});
