// Reports and account restrictions for everyone (27 Sep).
process.env.JWT_SECRET = 't'; process.env.PAYSTACK_SECRET_KEY = 't';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
// Admin switches: a stand-in returning nothing, so every switch uses its safe default (instant, no database).
{ const Setting = require(path.join(B, 'models/Setting')); Setting.findById = async () => null; }
const jwt = R('node_modules/jsonwebtoken'), express = R('node_modules/express'), bcrypt = R('node_modules/bcryptjs');
const Stylist = R('models/Stylist'), Customer = R('models/Customer'), Request = R('models/Request'), Report = R('models/Report');
const Notification = R('models/Notification'), AdminAction = R('models/AdminAction'), Conversation = R('models/Conversation'), Activity = R('models/Activity');
const attempts = R('lib/attempts'); attempts._setNowForTests(() => 1e12);
let seq = 0; const notes = [], audit = [];
const doc = (f) => ({ ...f, _id: { toString: () => f.id, toJSON: () => f.id }, save: async function () { return this; }, toObject() { const { toObject, save, ...r } = this; return { ...r }; } });
const hash = bcrypt.hashSync('right-password', 4);
const S = { adm: doc({ id: 'adm', name: 'Christopher', isAdmin: true, accountStatus: 'ACTIVE', styles: [] }), shop: doc({ id: 'shop', name: 'Etornam', salonName: 'Etornam Braids', phone: '+233544377501', status: 'APPROVED', accountStatus: 'ACTIVE', availability: 'AVAILABLE', styles: [{ id: 's1', name: 'Knotless', price: 300 }] }), other: doc({ id: 'other', name: 'Kofi', status: 'APPROVED', accountStatus: 'ACTIVE', styles: [] }) };
const C = { ama: doc({ id: 'ama', name: 'Ama', phone: '+233241112222', passwordHash: hash, accountStatus: 'ACTIVE' }), yaw: doc({ id: 'yaw', name: 'Yaw', phone: '+233209998888', passwordHash: hash, accountStatus: 'ACTIVE' }) };
const RQ = { b1: doc({ id: 'b1', stylistId: 'shop', clientId: 'ama', status: 'completed', serviceNameSnapshot: 'Knotless' }) };
const REP = {};
const get = (T) => async (id) => { if (String(id).includes('!')) throw new Error('Cast'); return T[String(id)] || null; };
const upd = (T) => async (id, u) => { if (String(id).includes('!')) throw new Error('Cast'); const d = T[String(id)]; if (!d) return null; Object.assign(d, u); return d; };
Stylist.findById = get(S); Customer.findById = get(C); Request.findById = get(RQ);
Stylist.findByIdAndUpdate = upd(S); Customer.findByIdAndUpdate = upd(C); Report.findByIdAndUpdate = upd(REP);
Customer.exists = async (f) => !!C[String(f._id)]; Customer.findOne = async (f) => Object.values(C).find((c) => f.phone.$in.includes(c.phone)) || null;
Report.create = async (f) => { const id = 'r' + (++seq); REP[id] = doc({ id, state: 'OPEN', createdAt: Date.now(), ...f }); return REP[id]; };
Report.find = () => { const l = Object.values(REP); const p = Promise.resolve(l); p.sort = () => Promise.resolve(l); return p; };
Request.create = async (f) => { const id = 'n' + (++seq); RQ[id] = doc({ id, ...f }); return RQ[id]; };
Request.countDocuments = async () => 0; Stylist.find = async (f) => (f && (f.isAdmin || f.$or) ? [S.adm] : []); Activity.create = async () => ({});
Conversation.findOne = async () => null; Conversation.create = async () => ({ _id: { toString: () => 'cv' }, save: async () => {} });
Notification.create = async (n) => { notes.push(n); return n; }; AdminAction.create = async (a) => { audit.push(a); return a; };
const app = express(); app.set('trust proxy', 1); app.use(express.json());
app.use('/api/reports', R('routes/reports')); app.use('/api/admin', R('routes/admin')); app.use('/api/stylists', R('routes/stylists'));
app.use('/api/requests', R('routes/requests')); app.use('/api/customers', R('routes/customers'));
app.use((err, req, res, next) => { console.log('SERVER ERROR', err.message); res.status(500).json({ error: 'x' }); });
const tok = (p) => jwt.sign(p, 't'); const ADMIN = tok({ id: 'adm', isAdmin: true }), SHOP = tok({ id: 'shop' }), OTHER = tok({ id: 'other' }), AMA = tok({ id: 'ama', role: 'customer' });
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
const server = app.listen(8225, async () => {
  let ipn = 0; const call = async (m, u, t, body, ip) => { const r = await fetch('http://localhost:8225' + u, { method: m, headers: { 'Content-Type': 'application/json', 'X-Forwarded-For': ip || ('10.0.0.' + (++ipn)), ...(t ? { Authorization: 'Bearer ' + t } : {}) }, body: body ? JSON.stringify(body) : undefined }); let j = {}; try { j = await r.json(); } catch (e) {} return { s: r.status, j }; };
  console.log('--- FILING A REPORT ---');
  let r = await call('POST', '/api/reports', null, { stylistId: 'shop', detail: 'bad' });
  check('a one-word report is refused (describe what happened)', r.s === 400);
  r = await call('POST', '/api/reports', null, { stylistId: 'shop', detail: 'x'.repeat(2001) });
  check('an over-long report is refused', r.s === 400);
  r = await call('POST', '/api/reports', null, { stylistId: 'made-up-shop', detail: 'She never showed up for my booking.' });
  check('report against a shop that does not exist → 404', r.s === 404);
  r = await call('POST', '/api/reports', AMA, { stylistId: 'shop', requestId: 'b1', category: 'NO_SHOW', detail: 'She never showed up for my booking.', urgent: 'yes' });
  const rep1 = Object.values(REP)[0];
  check('customer reports a shop about a booking: saved with category, booking, reporter', r.s === 200 && rep1.targetType === 'stylist' && rep1.targetId === 'shop' && rep1.requestId === 'b1' && rep1.category === 'NO_SHOW' && rep1.reporterId === 'ama');
  check('"urgent" only counts when it is truly true', rep1.urgent === false);
  check('admins are told', notes.some((n) => n.type === 'REPORT_FILED'));
  check('the reply does not echo the report back', !('detail' in r.j));
  r = await call('POST', '/api/reports', null, { detail: 'The app keeps logging me out, please help.' });
  check('a general report (no one named) is fine, no login needed', r.s === 200);
  for (let i = 0; i < 5; i++) await call('POST', '/api/reports', null, { detail: 'Spam spam spam spam ' + i }, '66.6.6.6');
  r = await call('POST', '/api/reports', null, { detail: 'Spam spam spam spam 6' }, '66.6.6.6');
  check('6th report from one address in 15 minutes → paused', r.s === 429);
  console.log('--- PROFESSIONALS REPORTING CUSTOMERS ---');
  r = await call('POST', '/api/reports', null, { targetType: 'customer', requestId: 'b1', detail: 'Customer was abusive to me.' });
  check('not logged in → cannot report a customer', r.s === 401);
  r = await call('POST', '/api/reports', AMA, { targetType: 'customer', requestId: 'b1', detail: 'Customer was abusive to me.' });
  check('a customer cannot report another customer', r.s === 401);
  r = await call('POST', '/api/reports', OTHER, { targetType: 'customer', requestId: 'b1', detail: 'Customer was abusive to me.' });
  check('a professional with NO booking with this customer → refused (no harassment by report)', r.s === 403);
  r = await call('POST', '/api/reports', SHOP, { targetType: 'customer', requestId: 'b1', category: 'HARASSMENT', detail: 'Customer was abusive to me.' });
  const rep2 = Object.values(REP).find((x) => x.targetType === 'customer');
  check('the shop that served her can report her', r.s === 200 && rep2 && rep2.targetId === 'ama' && rep2.reporterType === 'stylist');
  console.log('--- ADMIN REVIEWS ---');
  r = await call('GET', '/api/reports', SHOP);
  check('a normal professional cannot read reports (403)', r.s === 403);
  r = await call('GET', '/api/reports', ADMIN);
  const e1 = r.j.find((x) => x.requestId === 'b1' && x.targetType === 'stylist');
  check('admin sees who it is about, who filed it, and the booking', e1 && e1.target.name === 'Etornam Braids' && e1.reporter.name === 'Ama' && e1.booking.service === 'Knotless');
  r = await call('PUT', `/api/reports/${rep1.id}/state`, ADMIN, { state: 'MAGIC' });
  check('unknown state refused', r.s === 400);
  r = await call('PUT', `/api/reports/${rep1.id}/state`, ADMIN, { state: 'UNDER_REVIEW', adminNotes: 'Called both sides.' });
  check('admin moves it under review with a private note, logged', r.s === 200 && rep1.state === 'UNDER_REVIEW' && rep1.adminNotes === 'Called both sides.' && audit.some((a) => a.action === 'REPORT_STATE_CHANGED'));
  r = await call('PUT', '/api/reports/bad!id/state', ADMIN, { state: 'RESOLVED' });
  check('bad report id → clean 404', r.s === 404);
  console.log('--- RESTRICTING A CUSTOMER ---');
  r = await call('POST', '/api/admin/customers/ama/restrict', SHOP, { accountStatus: 'RESTRICTED', reason: 'Repeated no-shows' });
  check('a normal professional cannot restrict (403)', r.s === 403);
  r = await call('POST', '/api/admin/customers/ama/restrict', ADMIN, { accountStatus: 'RESTRICTED', reason: 'no' });
  check('restricting needs a clear reason', r.s === 400);
  r = await call('POST', '/api/admin/customers/ama/restrict', ADMIN, { accountStatus: 'RESTRICTED', reason: 'Repeated no-shows' });
  check('admin restricts Ama: she is told why, logged', r.s === 200 && C.ama.accountStatus === 'RESTRICTED' && notes.some((n) => n.recipientId === 'ama' && n.type === 'ACCOUNT_RESTRICTED' && n.message === 'Repeated no-shows') && audit.some((a) => a.action === 'ACCOUNT_RESTRICTED' && a.targetType === 'customer'));
  r = await call('POST', '/api/customers/login', null, { phone: '0241112222', password: 'right-password' });
  check('restricted (not suspended): she can still log in', r.s === 200);
  r = await call('POST', '/api/requests', AMA, { stylistId: 'shop', styleId: 's1', clientId: 'ama', clientName: 'Ama', clientPhone: '+233241112222', preferredAt: Date.now() + 86400000 });
  check('…but cannot book, and is told why', r.s === 403 && /Repeated no-shows/.test(r.j.error));
  r = await call('POST', '/api/customers/me/book-again/b1', AMA, {});
  check('…and cannot "book again" either', r.s === 403);
  await call('POST', '/api/admin/customers/ama/restrict', ADMIN, { accountStatus: 'SUSPENDED', reason: 'Threatened a professional' });
  r = await call('POST', '/api/customers/login', null, { phone: '0241112222', password: 'right-password' });
  check('suspended: cannot log in, told why', r.s === 403 && /suspended: Threatened a professional/.test(r.j.error));
  r = await call('POST', '/api/customers/login', null, { phone: '0241112222', password: 'wrong' });
  check('a wrong password still gets the usual answer (status not revealed)', r.s === 401 && !/suspended/.test(r.j.error));
  r = await call('POST', '/api/admin/customers/ama/restore', ADMIN);
  check('restored: active again, told', r.s === 200 && C.ama.accountStatus === 'ACTIVE' && notes.some((n) => n.recipientId === 'ama' && n.type === 'ACCOUNT_RESTORED'));
  console.log('--- RESTRICTING A PROFESSIONAL ---');
  r = await call('POST', '/api/stylists/shop/restrict', ADMIN, { accountStatus: 'RESTRICTED', reason: 'x' });
  check('professional restriction needs a clear reason too', r.s === 400);
  r = await call('POST', '/api/stylists/shop/restrict', ADMIN, { accountStatus: 'RESTRICTED', reason: 'Under investigation after reports' });
  check('the professional is told why', r.s === 200 && notes.some((n) => n.recipientId === 'shop' && n.type === 'ACCOUNT_RESTRICTED' && n.message === 'Under investigation after reports'));
  r = await call('POST', '/api/stylists/shop/restore', ADMIN);
  check('restored and told; the old reason is cleared', r.s === 200 && S.shop.accountStatus === 'ACTIVE' && S.shop.restrictionReason === null && notes.some((n) => n.recipientId === 'shop' && n.type === 'ACCOUNT_RESTORED'));
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); server.close(); process.exit(fail ? 1 : 0);
});
