// Login security: password guessing paused, and login never reveals who has an account (27 Sep).
process.env.JWT_SECRET = 't'; process.env.PAYSTACK_SECRET_KEY = 't';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
// Admin switches: a stand-in returning nothing, so every switch uses its safe default (instant, no database).
{ const Setting = require(path.join(B, 'models/Setting')); Setting.findById = async () => null; }
const express = R('node_modules/express'), bcrypt = R('node_modules/bcryptjs');
const Stylist = R('models/Stylist'), Customer = R('models/Customer'), PasswordResetRequest = R('models/PasswordResetRequest'), Notification = R('models/Notification');
const attempts = R('lib/attempts');
let T = 1_000_000_000_000; attempts._setNowForTests(() => T);
const hash = bcrypt.hashSync('right-password', 4);
const S = { pro: { _id: { toString: () => 'pro' }, name: 'Etornam', phone: '+233544377501', passwordHash: hash, accountStatus: 'ACTIVE', toObject() { return { name: 'Etornam' }; } } };
const C = { ama: { _id: { toString: () => 'ama' }, name: 'Ama', phone: '+233241112222', passwordHash: hash, toObject() { return { name: 'Ama' }; } } };
const byPhone = (Tb) => async (f) => Object.values(Tb).find((d) => f.phone.$in.includes(d.phone)) || null;
Stylist.findOne = byPhone(S); Customer.findOne = byPhone(C);
PasswordResetRequest.findOne = async () => null; PasswordResetRequest.create = async () => ({}); Notification.create = async () => ({});
Stylist.find = async () => [];
const app = express(); app.set('trust proxy', 1); app.use(express.json());
app.use('/api/auth', R('routes/auth')); app.use('/api/customers', R('routes/customers'));
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
const server = app.listen(8223, async () => {
  const post = async (u, body, ip = '1.1.1.1') => { const r = await fetch('http://localhost:8223' + u, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Forwarded-For': ip }, body: JSON.stringify(body) }); return { s: r.status, j: await r.json() }; };
  console.log('--- NOBODY CAN CHECK WHO USES SHEEBA ---');
  const a = await post('/api/auth/login', { phone: '0200000000', password: 'x' });
  const b = await post('/api/auth/login', { phone: '0544377501', password: 'wrong' });
  check('unknown number and wrong password get the SAME answer', a.s === 401 && b.s === 401 && a.j.error === b.j.error, a.j.error + ' | ' + b.j.error);
  check('the answer never says "no account"', !/no account|not found/i.test(a.j.error));
  const t0 = Date.now(); await post('/api/auth/login', { phone: '0209999999', password: 'x' }, '9.9.9.1'); const tUnknown = Date.now() - t0;
  const t1 = Date.now(); await post('/api/auth/login', { phone: '0544377501', password: 'nope' }, '9.9.9.2'); const tWrong = Date.now() - t1;
  check(`both take real password-checking time (${tUnknown} ms vs ${tWrong} ms)`, tUnknown >= 20 && tWrong >= 1);
  attempts._setNowForTests(() => T);
  console.log('--- PASSWORD GUESSING PAUSED ---');
  for (let i = 0; i < 4; i++) await post('/api/auth/login', { phone: '0544377501', password: 'guess' + i });
  let r = await post('/api/auth/login', { phone: '0544377501', password: 'right-password' });
  check('4 wrong, then right → logs in (and the count is cleared)', r.s === 200 && r.j.token);
  for (let i = 0; i < 5; i++) await post('/api/auth/login', { phone: '+233 54 437 7501', password: 'guess' + i });
  r = await post('/api/auth/login', { phone: '0544377501', password: 'right-password' });
  check('5 wrong (any number format) → paused, even the right password waits', r.s === 429 && /15 minutes/.test(r.j.error) && /Forgot password/.test(r.j.error), JSON.stringify(r.j));
  r = await post('/api/auth/login', { phone: '0544377501', password: 'right-password' }, '2.2.2.2');
  check('pause is on the ACCOUNT: another address is paused too', r.s === 429);
  r = await post('/api/customers/login', { phone: '0241112222', password: 'right-password' });
  check('other accounts are unaffected', r.s === 200);
  T += 16 * 60 * 1000;
  r = await post('/api/auth/login', { phone: '0544377501', password: 'right-password' });
  check('after 15 minutes the pause lifts', r.s === 200);
  console.log('--- ONE ADDRESS TRYING MANY NUMBERS ---');
  for (let i = 0; i < 20; i++) await post('/api/customers/login', { phone: `02400000${String(i).padStart(2, '0')}`, password: 'x' }, '6.6.6.6');
  r = await post('/api/customers/login', { phone: '0241112222', password: 'right-password' }, '6.6.6.6');
  check('20 failures from one address → that address is paused', r.s === 429);
  r = await post('/api/customers/login', { phone: '0241112222', password: 'right-password' }, '7.7.7.7');
  check("…but the real customer on another address isn't", r.s === 200);
  console.log("--- FORGOT PASSWORD CAN'T FLOOD THE ADMIN ---");
  for (let i = 0; i < 10; i++) await post('/api/auth/forgot-password', { phone: `05500000${String(i).padStart(2, '0')}` }, '8.8.8.8');
  r = await post('/api/auth/forgot-password', { phone: '0550000099' }, '8.8.8.8');
  check('11th request from one address in 15 minutes → paused', r.s === 429);
  r = await post('/api/auth/forgot-password', { phone: '0550000099' }, '4.4.4.4');
  check('a normal person on another address still gets help', r.s === 200 && r.j.ok);
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); server.close(); process.exit(fail ? 1 : 0);
});
