// Sign-up (professionals and customers) end to end, including where they came from.
process.env.JWT_SECRET = 't'; process.env.PAYSTACK_SECRET_KEY = 't';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
const express = R('node_modules/express');
const Stylist = R('models/Stylist'), Customer = R('models/Customer'), Activity = R('models/Activity'), Notification = R('models/Notification');
const Referral = R('models/Referral'), Counter = R('models/Counter'), Setting = R('models/Setting');
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
let seq = 20; const pros = [], custs = [], notes = [];
const doc = (f) => ({ ...f, _id: { toString: () => f.id, toJSON: () => f.id }, toObject() { const { toObject, ...r } = this; return JSON.parse(JSON.stringify(r)); }, save: async function () { return this; } });
const boss = doc({ id: 'boss', name: 'Kwame', code: 'KWAME0003', memberNumber: 3, role: 'PROFESSIONAL', isAdmin: true, accountStatus: 'ACTIVE' });
Stylist.findOne = async (f) => (f.phone ? pros.find((p) => f.phone.$in.includes(p.phone)) || null : (f.code === 'KWAME0003' || (f.$or && JSON.stringify(f).includes('KWAME0003')) ? boss : null));
Stylist.find = async () => [boss];
Stylist.create = async (f) => { const d = doc({ id: 'p' + pros.length, ...f }); pros.push(d); return d; };
Customer.findOne = async (f) => custs.find((c) => f.phone.$in.includes(c.phone)) || null;
Customer.create = async (f) => { const d = doc({ id: 'c' + custs.length, ...f }); custs.push(d); return d; };
Counter.findById = async () => ({ _id: 'members', seq });
Counter.findOneAndUpdate = async () => ({ seq: ++seq });
Setting.findOne = async () => null; Setting.findById = async () => null;
Activity.create = async () => ({}); Notification.create = async (n) => { notes.push(n); return n; };
Referral.findOne = async (f) => (f.code === 'TT-OCT' ? { code: 'TT-OCT', stylistId: 'boss', channel: 'TIKTOK', active: true } : null);
const app = express(); app.set('trust proxy', 1); app.use(express.json());
app.use('/api/auth', R('routes/auth')); app.use('/api/customers', R('routes/customers'));
app.use((err, req, res, next) => { console.log('SERVER ERROR', err.message); res.status(500).json({ error: 'x' }); });
const server = app.listen(0, async () => {
  const port = server.address().port; let ip = 0;
  const post = async (u, body) => { const r = await fetch(`http://localhost:${port}${u}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Forwarded-For': '10.1.0.' + (++ip) }, body: JSON.stringify(body) }); return { s: r.status, j: await r.json() }; };
  console.log('--- PROFESSIONALS ---');
  let r = await post('/api/auth/register', { phone: '0241110001', password: 'goodpass1', name: 'Abena', country: 'GH', source: { type: 'link', code: 'TT-OCT' } });
  check('a professional signs up through a TikTok marketing link', r.s === 200 && r.j.token && pros[0].phone === '+233241110001');
  check('…their source is saved: link, TikTok, from Kwame\'s shop', pros[0].signupSource && pros[0].signupSource.type === 'link' && pros[0].signupSource.channel === 'TIKTOK' && pros[0].signupSource.shopId === 'boss');
  check('…they get the next member number and a friendly code', pros[0].memberNumber === 21 && /^ABENA0021$/.test(pros[0].code));
  check('…they start hidden until approved, and the admin is told', pros[0].status === 'UNDER_REVIEW' && notes.some((n) => n.type === 'SHOP_UNDER_REVIEW'));
  check('…the reply never includes the password hash', !JSON.stringify(r.j).includes('passwordHash'));
  r = await post('/api/auth/register', { phone: '0241110002', password: 'goodpass1', name: 'Kofi', country: 'GH' });
  check('a professional with NO source still signs up (source is simply empty)', r.s === 200 && pros[1].signupSource === null);
  r = await post('/api/auth/register', { phone: '0241110003', password: 'goodpass1', name: 'Esi', country: 'GH', role: 'APPRENTICE', supervisorCode: 'KWAME0003', source: { type: 'invite', code: 'KWAME0003' } });
  check('an apprentice signs up with their supervisor\'s code (source: invite)', r.s === 200 && pros[2].role === 'APPRENTICE' && pros[2].supervisorId === 'boss' && pros[2].signupSource.type === 'invite');
  r = await post('/api/auth/register', { phone: '+233 24 111 0001', password: 'goodpass1', name: 'Again', country: 'GH' });
  check('the same number again (any format) is refused', r.s === 400 && /already exists/.test(r.j.error));
  r = await post('/api/auth/register', { phone: '0241110009', password: 'goodpass1', country: 'GH' });
  check('a missing name is refused', r.s === 400);
  r = await post('/api/auth/register', { phone: '0241110010', password: 'goodpass1', name: 'Junk', country: 'GH', source: { type: 'evil', code: '<script>' } });
  check('a junk source is ignored, sign-up still works', r.s === 200 && pros[pros.length - 1].signupSource === null);
  console.log('--- CUSTOMERS ---');
  r = await post('/api/customers/register', { phone: '0551110001', password: 'goodpass1', name: 'Ama', country: 'GH', source: { type: 'look', shopId: 'boss', referrerHost: 'instagram.com' } });
  check('a customer signs up from a shared "Book this look" card, via Instagram', r.s === 200 && r.j.token && custs[0].signupSource.type === 'look' && custs[0].signupSource.referrerHost === 'instagram.com');
  check('…with the next member number', custs[0].memberNumber === seq);
  r = await post('/api/customers/register', { phone: '0551110002', password: 'goodpass1', name: 'Yaw', country: 'GH' });
  check('a customer with no source still signs up', r.s === 200 && custs[1].signupSource === null);
  r = await post('/api/customers/register', { phone: '0551110001', password: 'goodpass1', name: 'Twice', country: 'GH' });
  check('the same customer number again is refused', r.s === 400);
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); server.close(); process.exit(fail ? 1 : 0);
});
