// Where sign-ups and bookings come from (lib/source.js, bookings, admin Sources).
process.env.JWT_SECRET = 't'; process.env.PAYSTACK_SECRET_KEY = 't';
const path = require('path'); const B = path.join(__dirname, '..');
const R = (m) => require(path.join(B, m));
require(path.join(B, 'node_modules/express-async-errors'));
// Admin switches: a stand-in returning nothing, so every switch uses its safe default (instant, no database).
{ const Setting = require(path.join(B, 'models/Setting')); Setting.findById = async () => null; }
const jwt = R('node_modules/jsonwebtoken'), express = R('node_modules/express');
const Stylist = R('models/Stylist'), Customer = R('models/Customer'), Request = R('models/Request'), Activity = R('models/Activity');
const Referral = R('models/Referral'), FieldVisit = R('models/FieldVisit'), Notification = R('models/Notification'), Conversation = R('models/Conversation');
const { resolveSource } = R('lib/source');
const attempts = R('lib/attempts'); attempts._setNowForTests(() => 1e12);
let pass = 0, fail = 0; const check = (l, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + ' | ' + l + (c ? '' : '  ' + x)); };
const REFS = [{ code: 'WA-SEPT', stylistId: 'shop', channel: 'WHATSAPP', label: 'WhatsApp September', active: true }, { code: 'OTHERS', stylistId: 'other', channel: 'INSTAGRAM', label: 'Theirs', active: true }];
Referral.findOne = async (f) => REFS.find((r) => r.code === f.code && r.active && (!f.stylistId || r.stylistId === f.stylistId)) || null;
Referral.find = async (f) => REFS.filter((r) => f.code.$in.includes(r.code));
(async () => {
  console.log('--- CLEANING A SOURCE ---');
  check('an unknown kind of source is ignored', (await resolveSource({ type: 'hacker', code: 'x' })) === null);
  check('nothing sent → nothing recorded', (await resolveSource(undefined)) === null);
  let s = await resolveSource({ type: 'link', code: 'WA-SEPT', channel: 'FAKE' });
  check('a real marketing link: channel and shop come from the LINK, not the browser', s.type === 'link' && s.channel === 'WHATSAPP' && s.shopId === 'shop');
  s = await resolveSource({ type: 'link', code: 'MADE-UP', shopId: 'shop' });
  check('a made-up link code becomes "shop" (no fake credit)', s.type === 'shop' && s.code === null);
  s = await resolveSource({ type: 'direct', at: 99e15, referrerHost: 'x'.repeat(200) });
  check('a date in the future is dropped; long text is trimmed', s.at === null && s.referrerHost.length === 80);

  console.log('--- A BOOKING REMEMBERS WHERE IT CAME FROM ---');
  const acts = [], made = [];
  Stylist.findById = async (id) => (id === 'shop' ? { _id: { toString: () => 'shop' }, name: 'Etornam', status: 'APPROVED', accountStatus: 'ACTIVE', availability: 'AVAILABLE', styles: [{ id: 's1', name: 'Knotless', price: 300 }] } : null);
  Stylist.find = async () => [];
  Customer.exists = async () => false; Customer.findById = async () => null;
  Request.create = async (f) => { made.push(f); return { ...f, _id: { toString: () => 'r' + made.length } }; };
  Request.countDocuments = async () => 0;
  Activity.create = async (a) => { acts.push(a); return a; };
  Notification.create = async () => ({}); Conversation.findOne = async () => null;
  const app = express(); app.use(express.json()); app.use('/api/requests', R('routes/requests'));
  app.use((err, req, res, next) => { console.log('SERVER ERROR', err.message); res.status(500).json({ error: 'x' }); });
  const server = app.listen(0);
  const port = server.address().port;
  const book = (source) => fetch(`http://localhost:${port}/api/requests`, { method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ stylistId: 'shop', styleId: 's1', clientId: 'anon-' + Math.random(), clientName: 'Ama', clientPhone: '0241112222', preferredAt: Date.now() + 86400000, source }) });
  let r = await book({ type: 'link', code: 'WA-SEPT' });
  check('booked through "WhatsApp September": source saved with its channel', r.status === 200 && made[0].source.type === 'link' && made[0].source.channel === 'WHATSAPP');
  check('…and the link is credited with a booking', acts.some((a) => a.type === 'REFERRED_REQUEST_CREATED' && a.meta.code === 'WA-SEPT'));
  acts.length = 0;
  await book({ type: 'link', code: 'OTHERS' });
  check("another shop's link code gets NO credit here", !acts.some((a) => a.type === 'REFERRED_REQUEST_CREATED'));
  await book({ type: 'look', shopId: 'shop' });
  check('a shared "Book this look" card is recorded as "look"', made[made.length - 1].source.type === 'look');
  server.close();

  console.log('--- ADMIN: SOURCES ---');
  const shops = [{ signupSource: { type: 'link', channel: 'TIKTOK' } }, { signupSource: { type: 'invite' } }, { signupSource: null }];
  const custs = [{ signupSource: { type: 'look', referrerHost: 'instagram.com' } }, { signupSource: { type: 'look', referrerHost: 'instagram.com' } }, { signupSource: { type: 'direct' } }];
  const reqs = [{ source: { type: 'link', channel: 'WHATSAPP' }, stylistId: 'shop' }, { source: { type: 'look' }, stylistId: 'shop' }, { source: { type: 'shop' }, stylistId: 'shop' }, { source: { type: 'rebook' }, stylistId: 'shop' }, { source: null, stylistId: 'shop' }];
  let reqFilter = null;
  Stylist.find = async (f) => (f && f._id ? [{ _id: { toString: () => 'shop' }, name: 'Etornam', salonName: 'Etornam Braids' }] : shops);
  Stylist.findById = async (id) => (id === 'adm' ? { isAdmin: true, accountStatus: 'ACTIVE' } : null);
  Customer.find = async () => custs;
  Request.find = async (f) => { reqFilter = f; return reqs; };
  Activity.find = async () => [{ type: 'REFERRAL_VISIT', meta: { code: 'WA-SEPT' } }, { type: 'REFERRAL_VISIT', meta: { code: 'WA-SEPT' } }, { type: 'REFERRED_REQUEST_CREATED', meta: { code: 'WA-SEPT' } }];
  FieldVisit.find = async () => [{ signedUpStylistId: 'a' }, { signedUpStylistId: 'b' }, { signedUpStylistId: 'a' }];
  const app2 = express(); app2.use(express.json()); app2.use('/api/analytics', R('routes/analytics'));
  const s2 = app2.listen(0); const p2 = s2.address().port;
  const get = async (t) => { const x = await fetch(`http://localhost:${p2}/api/analytics/sources?days=30`, { headers: t ? { Authorization: 'Bearer ' + t } : {} }); return { s: x.status, j: await x.json() }; };
  check('only admins with analytics can see sources', (await get(jwt.sign({ id: 'someone' }, 't'))).s === 403);
  r = await get(jwt.sign({ id: 'adm' }, 't'));
  const o = r.j;
  check('bookings are counted by their NUMBER timestamps (not a Date, which would match nothing)', typeof reqFilter.createdAt.$gte === 'number');
  check('sign-ups by source: professionals from a link, an invite, and 1 from before sources existed', o.signups.professionals.total === 3 && o.signups.professionals.byType.some((x) => x.key === 'unknown'));
  check('…which link channel: TikTok', o.signups.professionals.linkChannels[0].key === 'TIKTOK');
  check('customers: 2 from shared looks, referred by instagram.com', o.signups.customers.byType[0].key === 'look' && o.signups.customers.byType[0].count === 2 && o.signups.referrerSites[0].key === 'instagram.com');
  check('2 different shops signed up in person on field trips', o.signups.inPersonFieldWork === 2);
  check('bookings by source (5), WhatsApp among link bookings', o.bookings.total === 5 && o.bookings.linkChannels[0].key === 'WHATSAPP');
  check('"WhatsApp September": 2 visits, 1 booking, Etornam Braids', o.marketingLinks[0].label === 'WhatsApp September' && o.marketingLinks[0].visits === 2 && o.marketingLinks[0].bookings === 1 && o.marketingLinks[0].shop === 'Etornam Braids');
  check("shops whose shared links bring bookings: Etornam Braids (2)", o.shopsBringingBookings[0].name === 'Etornam Braids' && o.shopsBringingBookings[0].count === 2);
  s2.close();
  console.log('\n' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
})();
